
---
# Jenkins doesn't allow updates via CLI, though that is required before plugins
# can be installed via CLI. See: https://gist.github.com/rowan-m/1026918
- name: Jenkins | Create Jenkins updates folder.
  file:
    path: /var/lib/jenkins/updates
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory

- name: Jenkins | Update Jenkins plugin data.
  shell: >
    curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
    creates=/var/lib/jenkins/updates/default.json
  sudo: yes


- name: Jenkins | Permissions for default.json updates info.
  file:
    path: /var/lib/jenkins/updates/default.json
    owner: jenkins
    group: jenkins
    mode: 0755
  sudo: yes

- name: Jenkins | Install Jenkins plugins.
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:8080{{ jenkins_url_prefix | default('') }}/ install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: jenkins_plugins
  become: yes
  become_user: jenkins
  notify: restart jenkins
